# Amfora Configuration - Kunal Kumar
# General Settings
[a-general]
home = "about:newtab"

# Follow up to 5 Gemini redirects without prompting.
# A prompt is always shown after the 5th redirect and for redirects to protocols other than Gemini.
auto_redirect = false

# What command to run to open a HTTP(S) URL.
http = 'xdg-open'

# Any URL that will accept a query string can be put here
search = "gemini://geminispace.info/search"

# Whether colors will be used in the terminal
color = true

# Whether ANSI color codes from the page content should be rendered
ansi = true

# Whether to replace list asterisks with unicode bullets
bullets = true

# Whether to show link after link text
show_link = false

# A number from 0 to 1, indicating what percentage of the terminal width the left margin should take up.
left_margin = 0.15

# The max number of columns to wrap a page's text to. Preformatted blocks are not wrapped.
max_width = 100

# 'downloads' is the path to a downloads folder.
downloads = 'Downloads/Amfora'

# Max size for displayable content in bytes - after that size a download window pops up
page_max_size = 2097152  # 2 MiB

# Max time it takes to load a page in seconds - after that a download window pops up
page_max_time = 10

# When a scrollbar appears. "never", "auto", and "always" are the only valid values.
scrollbar = "auto"

# Underline non-gemini URLs
underline = true

# Personal Keybindings
[keybindings]
bind_home = "H"
bind_bookmarks = "B"
bind_add_bookmark = "AB"
bind_reload = "R"
bind_new_tab = "N"
bind_close_tab = "X"
bind_next_tab = "t"
bind_prev_tab = "T"
bind_quit = "q"
bind_beginning = ":"
bind_end = "E:"

# URL Handling
[url-handlers]
other = 'default'

# Caching
[cache]
max_size = 0  # Size in bytes
max_pages = 30 # The maximum number of pages the cache will store

# How long a page will stay in cache, in seconds.
timeout = 1800 # 30 mins
