name: Bug Report
description: Submit a Bug Report
title: "Bug: "
labels: ["bug"]
body:
  - type: textarea
    attributes:
      label: Describe the bug
      description: A clear description of what is the bug.
    validations:
      required: true
  
  - type: textarea
    attributes: 
      label: Steps to reproduce
      description: Explain in bullet points, that how we reproduce the bug.      

  - type: textarea
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?

  - type: input
    attributes:
      label: Operating System
      description: What operating system are you using and which version?
      placeholder: ex. Fedora 38 or Ubuntu 22.04
    validations:
      required: true

  - type: checkboxes
    attributes:
      label: Self Contribution?
      description: Are you going to work on this issue yourself for contributing to the project?
      options: 
        - label: Yes, I will work on it myself.
        - label: No, I won't work on it.

  - type: textarea
    attributes:
      label: Contact Details
      description: How can we get in contact with you for more information?
      placeholder: ex. example@gmail.com
    validations:
      required: true
  
  - type: textarea
    attributes:
      label: Additional Information
      description: Any additional information you think may be important
